<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Unified version for all packages -->
    <PackageVersion Include="Cadmus.Ndp.Parts" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Ndp.Parts.Test" Version="15.0.0" />
    <PackageVersion Include="Cadmus.NdpBooks.Parts" Version="15.0.0" />
    <PackageVersion Include="Cadmus.NdpBooks.Parts.Test" Version="15.0.0" />
    <PackageVersion Include="Cadmus.NdpDrawings.Parts" Version="15.0.0" />
    <PackageVersion Include="Cadmus.NdpDrawings.Parts.Test" Version="15.0.0" />
    <PackageVersion Include="Cadmus.NdpFrac.Parts" Version="15.0.0" />
    <PackageVersion Include="Cadmus.NdpFrac.Parts.Test" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Seed.Ndp.Parts" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Seed.Ndp.Parts.Test" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Seed.NdpBooks.Parts" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Seed.NdpBooks.Parts.Test" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Seed.NdpDrawings.Parts" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Seed.NdpDrawings.Parts.Test" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Seed.NdpFrac.Parts" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Seed.NdpFrac.Parts.Test" Version="15.0.0" />
    <PackageVersion Include="CadmusNdpApi" Version="15.0.0" />
    <!-- External dependencies for all packages -->
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="Cadmus.Api.Config" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Api.Controllers" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Api.Controllers.Export" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Api.Controllers.Import" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Api.Models" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Api.Services" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Codicology.Graph" Version="9.0.5" />
    <PackageVersion Include="Cadmus.Codicology.Parts" Version="9.0.5" />
    <PackageVersion Include="Cadmus.Core" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Graph.Extras" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Iconography.Parts" Version="1.0.3" />
    <PackageVersion Include="Cadmus.Iconography.Services" Version="1.0.3" />
    <PackageVersion Include="Cadmus.Mat.Bricks" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Refs.Bricks" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Epigraphy.Parts" Version="9.0.4" />
    <PackageVersion Include="Cadmus.Seed" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Seed.Codicology.Parts" Version="9.0.5" />
    <PackageVersion Include="Cadmus.Seed.Epigraphy.Parts" Version="9.0.4" />
    <PackageVersion Include="Cadmus.Seed.General.Parts" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Seed.Iconography.Parts" Version="1.0.3" />
    <PackageVersion Include="Cadmus.Seed.Philology.Parts" Version="15.0.0" />
    <PackageVersion Include="Cadmus.Seed.TaxoStore.Parts" Version="0.0.5" />
    <PackageVersion Include="Cadmus.TaxoStore.Parts" Version="0.0.5" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="CsvHelper" Version="33.1.0" />
    <PackageVersion Include="DiffMatchPatch" Version="5.0.0" />
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageVersion Include="Fusi.Antiquity" Version="6.0.0" />
    <PackageVersion Include="Fusi.Api.Auth.Controllers" Version="7.0.3" />
    <PackageVersion Include="Fusi.Api.Auth.Models" Version="7.0.3" />
    <PackageVersion Include="Fusi.DbManager" Version="6.0.1" />
    <PackageVersion Include="Fusi.DbManager.PgSql" Version="6.0.3" />
    <PackageVersion Include="Fusi.Microsoft.Extensions.Configuration.InMemoryJson" Version="5.0.0" />
    <PackageVersion Include="Fusi.Text" Version="7.0.2" />
    <PackageVersion Include="Fusi.Tools" Version="8.0.4" />
    <PackageVersion Include="Fusi.Tools.Configuration" Version="8.0.3" />
    <PackageVersion Include="Fusi.Xml" Version="7.0.1" />
    <PackageVersion Include="Fusi.Xml.Extras" Version="7.0.1" />
    <PackageVersion Include="JmesPath.Net" Version="1.1.0" />
    <PackageVersion Include="Markdig" Version="1.3.2" />
    <PackageVersion Include="McMaster.NETCore.Plugins" Version="2.0.0" />
    <PackageVersion Include="MessagingApi" Version="6.0.0" />
    <PackageVersion Include="MessagingApi.SendGrid" Version="6.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Authorization" Version="10.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Physical" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="Mol.Api.Controllers" Version="0.0.7" />
    <PackageVersion Include="Mol.Import" Version="0.0.7" />
    <PackageVersion Include="Mol.PgSql" Version="0.0.7" />
    <PackageVersion Include="MongoDB.Bson" Version="3.9.0" />
    <PackageVersion Include="MongoDB.Driver" Version="3.9.0" />
    <PackageVersion Include="Mufi.Api.Controllers" Version="2.0.1" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageVersion Include="NPOI" Version="2.8.0" />
    <PackageVersion Include="Polly" Version="8.7.0" />
    <PackageVersion Include="Proteus.Core" Version="13.0.3" />
    <PackageVersion Include="Proteus.Entries" Version="13.0.3" />
    <PackageVersion Include="Proteus.Text.Xml" Version="13.0.3" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.16.16" />
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="Serilog.Sinks.Postgresql.Alternative" Version="4.2.0" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageVersion Include="SqlKata.Execution" Version="4.0.1" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageVersion Include="TaxoStore.Api.Controllers" Version="0.0.5" />
    <PackageVersion Include="TaxoStore.Core" Version="0.0.5" />
    <PackageVersion Include="TaxoStore.PgSql" Version="0.0.5" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>