services:
  # MongoDB
  cadmus-ndp-mongo:
    image: mongo
    container_name: cadmus-ndp-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null
    ports:
      - 27017:27017
    networks:
      - cadmus-ndp-network

  # PostgreSQL
  cadmus-ndp-pgsql:
    image: postgres
    container_name: cadmus-ndp-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-ndp-network

  # Mongo Express, optional web-based MongoDB admin interface
  mongo-express:
    image: mongo-express
    container_name: ndp-mongo-express
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=cadmus-ndp-mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - cadmus-ndp-mongo
    networks:
      - cadmus-ndp-network

  # Cadmus ndp API
  cadmus-ndp-api:
    image: vedph2020/cadmus-ndp-api:2.0.11
    container_name: cadmus-ndp-api
    ports:
      - 5172:8080
    depends_on:
      - cadmus-ndp-mongo
      - cadmus-ndp-pgsql
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-ndp-mongo:27017/{0}
      - CONNECTIONSTRINGS__AUTH=Server=cadmus-ndp-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-ndp-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__MOL=Server=cadmus-ndp-pgsql;port=5432;Database=mol;User Id=postgres;Password=postgres;Include Error Detail=True
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-ndp-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
      - SEED__DELAY=20
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
    networks:
      - cadmus-ndp-network

networks:
  cadmus-ndp-network:
    driver: bridge
